//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordCalcClient.WordCalcService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WordCalcService.IWCService")]
    public interface IWCService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCService/WordCalculateText", ReplyAction="http://tempuri.org/IWCService/WordCalculateTextResponse")]
        System.Collections.Generic.Dictionary<string, int> WordCalculateText(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCService/WordCalculateText", ReplyAction="http://tempuri.org/IWCService/WordCalculateTextResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> WordCalculateTextAsync(string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCServiceChannel : WordCalcClient.WordCalcService.IWCService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCServiceClient : System.ServiceModel.ClientBase<WordCalcClient.WordCalcService.IWCService>, WordCalcClient.WordCalcService.IWCService {
        
        public WCServiceClient() {
        }
        
        public WCServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<string, int> WordCalculateText(string text) {
            return base.Channel.WordCalculateText(text);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> WordCalculateTextAsync(string text) {
            return base.Channel.WordCalculateTextAsync(text);
        }
    }
}
